version: "3"
services:
  # Web service layer
  nginx:
    image: nginx:1.13
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:80"
    depends_on:
      - php

  # Application service layer
  php:
    build:
      context: ./php
    volumes:
      - "./app:/var/www/html"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=123.456

  # Data persistence service layer
  mysql:
    image: mysql:5.7
    volumes:
      - "db_data3:/var/lib/mysql"
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456

  # Helpers
  composer:
    image: composer:2    
    command: ["composer", "install"]
    depends_on:
      - php
    volumes:
      - "./app:/app"

volumes:
  db_data3:
